complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
filesize_format = "B"
filesize_metric = true
nonzero_exit_errors = true
path = ["/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/bin", "/usr/local/bin", "/home/kais_ubuntu/.cargo/bin", "/usr/local/sbin", "/usr/local/bin", "/usr/sbin", "/usr/bin", "/sbin", "/bin", "/usr/games", "/usr/local/games"]
pivot_mode = "auto"
plugin_dirs = ["D:\\Src\\GitHub\\nu-plugin-lib\\samples\\Nu.Plugin.Len\\bin\\Debug\\netcoreapp3.1"]
prompt = "starship prompt"
rm_always_trash = true
skip_welcome_message = false
startup = ["alias l = exa", "alias z = zsh", "alias la = exa -a", "alias ll = exa -la", "alias mv = mv -i", "alias rm = rm -i", "alias cp = cp -i", "alias gs = git status", "alias python = python3", "alias cl = clear", "alias fd = fdfind", "alias bat = batcat", "alias vi = nvim -u ~/.SpaceVim/vimrc"]

table_mode = "other"



[color_config]
header_align = "l"
header_bold = true
header_color = "c"
index_color = "rd"
leading_trailing_space_bg = "white"
primitive_binary = "cyan"
primitive_boolean = "green"
primitive_columnpath = "cyan"
primitive_date = "ru"
primitive_decimal = "red"
primitive_duration = "blue"
primitive_filesize = "yellow"
primitive_int = "green"
primitive_line = "yellow"
primitive_path = "yellow"
primitive_pattern = "white"
primitive_range = "purple"
primitive_string = "pb"
separator_color = "purple"

[env]
CMD_DURATION_MS = "7"
EDITOR = "vim"
HISTCONTROL = "ignoreboth"
HOME = "/home/kais_ubuntu"
HOSTTYPE = "x86_64"
KEYTIMEOUT = "1"
LANG = "C.UTF-8"
LESS = "-R"
LOGNAME = "kais_ubuntu"
LSCOLORS = "Gxfxcxdxbxegedabagacad"
LS_COLORS = "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
NAME = "TABLET-MVISCRCQ"
OLDPWD = "/home/kais_ubuntu"
PAGER = "less"
PWD = "/home/kais_ubuntu/.config/nu"
SHELL = "/usr/bin/zsh"
SHLVL = "14"
TERM = "xterm-256color"
UPDATE_ZSH_DAYS = "13"
USER = "kais_ubuntu"
WSLENV = "WT_SESSION::WT_PROFILE_ID"
WSL_DISTRO_NAME = "Ubuntu"
WSL_INTEROP = "/run/WSL/16896_interop"
WT_PROFILE_ID = "{2c4de342-38b7-51cf-b940-2309a097f518}"
WT_SESSION = "9b7cbab7-5098-4e6a-94a8-9c2c7ca8f229"
ZSH = "/home/kais_ubuntu/.oh-my-zsh"
_ = "/home/kais_ubuntu/.cargo/bin/nu"

[line_editor]
auto_add_history = true
bell_style = "audible"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "circular"
edit_mode = "emacs"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"
