#!/bin/bash
#download Ubuntu packages
cd
cd Downloads/
#sudo -i
sudo apt update
sudo apt upgrade -y
sudo apt install dos2unix tmux curl fd-find ripgrep zsh-syntax-highlighting zsh-autosuggestions software-properties-common apt-transport-https wget npm xterm libpangox-1.0-0 neovim zsh tldr gnome-terminal redshift-gtk mysql-server nodejs python3 python3-pip putty filezilla snap -y

#install pip packages
pip3 install beautifulsoup4 requests numpy pandas scikit-learn pillow matplotlib plotly seaborn scipy -y

#download third party apps (chrome, vscode)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
sudo apt install cargo
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb -y
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt update
sudo apt install code -y
git clone https://github.com/SpaceVim/SpaceVim.git ~/.SpaceVim
sh -c "$(curl -fsSL https://starship.rs/install.sh)"

#install snap packages
snap install spotify

#remove default packages
sudo apt remove firefox -y
sudo apt autoremove -y
rm -rf google-chrome-stable_current_amd64.deb
sudo apt update
sudo apt upgrade -y

#copy dot files to home folder
chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp .vimrc .zshrc .Xresources ~/
cp config.toml ~/.config/nu/
cp init.toml ~/Spacevim.d/
cp starship.toml ~/.config/

#fix file formatting and source configurations
cd
dos2unix .vimrc
dos2unix .Xresources
dos2unix .zshrc
dos2unix config.toml
dos2unix init.toml
source ~/.vimrc
#source ~/.bashrc
source ~/.zshrc
xrdb -merge ~/.Xresources

#install rust applications
rustup update
cargo install nu sd ytop grex sellij
wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rust-exa/exa_0.9.0-4_amd64.deb
sudo apt-get install ./exa_0.9.0-4_amd64.deb
sh -c "$(curl -fsSL https://starship.rs/install.sh)" - y
nu
config set prompt "starship prompt"
sudo apt install bat
sudo dpkg -i --force-overwrite /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb
sudo apt -f install
